name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Match this with the Node.js version you're using locally

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build  # Ensure you have a build script in your package.json

      - name: Start server
        run: npm run start-server &
        env:
          PORT: 8080

      - name: Wait for server to start
        run: sleep 10  # Adjust sleep duration based on how long your server takes to start

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start-server
