name: Run Cypress Tests

# Trigger the workflow on every push and pull request to main branch
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run