name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start backend server
        run: npm run start:backend &
        env:
          NODE_ENV: test

      - name: Start frontend server
        run: npm run start:frontend &
        env:
          NODE_ENV: test

      - name: Wait for servers to be ready
        run: sleep 10

      - name: Run Cypress tests
        run: npx cypress run