name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build # Building the frontend

      - name: Start server
        run: npm run start-server &
        env:
          PORT: 5500

      - name: Wait for server to start
        run: sleep 15 # Wait time adjusted to ensure the server is up

      - name: Cypress run
        run: npx cypress run --spec "cypress/e2e/firstTest.cy.js"
