name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Wait for deployment
        run: sleep 60 # Wait for 60 seconds to ensure deployment

      - name: Run Cypress tests
        run: npx cypress run --env --debug baseUrl=qa-site-nine.vercel.app

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     wait-on: "https://notwhoyourethinkingof.github.io/qa-site"
      #     wait-on-timeout: 60
