name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start http-server
        run: |
          npx http-server ./frontend/src -p 8080 &
          sleep 15

      - name: Check server response
        run: curl -I http://127.0.0.1:8080/frontend/src/index.html

      - name: Run Cypress tests
        run: npx cypress run --browser electron